version: '3'
services:
  goto:
    build: .
    image: linmounong/goto
    restart: always
    volumes:
      - goto:/var/goto
    command: -db /var/goto/goto.db
    ports:
      - 80:8096

volumes:
  goto:
